---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-api-skeleton # unique key of the deployment instance
spec:
    replicas: 3
    selector:
        matchLabels: # labels are used as mappings in the system
            app: go-api-skeleton
    template:
        metadata:
            labels:
                app: go-api-skeleton
        spec: # spec for container must have at least one
            containers:
            - name: go-api-skeleton # dash used to list
              image: zhanlianguf/go-api-skeleton:v1.0
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 80 # number of port to be exposed on the pod's IP address. What is a good port number for pods?
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
      - name: jenkins-home
        emptyDir: { }