# expose pods to service apiVersion: v1
---
apiVersion: v1
kind: Service
metadata:  
    name: go-api-skeleton
spec:
    type: LoadBalancer # "LoadBalancer" builds on NodePort and creates an external load-balancer (if supported in the current cloud) which routes to the same endpoints as the clusterIP.
    ports:
    - name: http
      port: 80 # the port that will be exposed by the service
      targetPort: 80 # number of the port to access on the pods targeted by the service
    selector: # Route service traffic to pods with label keys and values matching this selector
      app: go-api-skeleton
